sudo: required
services:
    - docker
language: python
matrix:
    include:
        # Linux builds
        - os: linux
          python: 2.7
        - os: linux
          python: 3.4
        - os: linux
          python: 3.5
        - os: linux
          python: 3.6

        - os: osx
          language: generic
          env: PYTHON=2.7
        - os: osx
          language: generic
          env: PYTHON=3.4
        - os: osx
          language: generic
          env: PYTHON=3.5
        - os: osx
          language: generic
          env: PYTHON=3.6

install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
          git clone https://github.com/MacPython/terryfy;
          source terryfy/travis_tools.sh;
          get_python_environment macpython $PYTHON;
      fi
    - pip install -r requirements.txt

script:
    - python setup.py test
