environment:
  matrix:
    # Python 2.7
    - PYTHON: "C:\\Python27"
      MINICONDA: C:\Miniconda
      PYTHON_VERSION: 2.7
    - PYTHON: "C:\\Python27-x64"
      MINICONDA: C:\Miniconda
      PYTHON_VERSION: 2.7

    # Python 3.4
    - PYTHON: "C:\\Python34"
      MINICONDA: C:\Miniconda3
      PYTHON_VERSION: 3.4
    - PYTHON: "C:\\Python34-x64"
      MINICONDA: C:\Miniconda3
      PYTHON_VERSION: 3.4

    # Python 3.5
    - PYTHON: "C:\\Python35"
      MINICONDA: C:\Miniconda35
      PYTHON_VERSION: 3.5
    - PYTHON: "C:\\Python35-x64"
      MINICONDA: C:\Miniconda35
      PYTHON_VERSION: 3.5

    # Python 3.6
    - PYTHON: "C:\\Python36"
      MINICONDA: C:\Miniconda36
      PYTHON_VERSION: 3.6
    - PYTHON: "C:\\Python36-x64"
      MINICONDA: C:\Miniconda36
      PYTHON_VERSION: 3.6

install:
  # Add conda onto the path
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # We need to install numpy, scipy and matplotlib through conda
  - "conda create -q -n test-environment python=%PYTHON_VERSION% numpy scipy matplotlib"
  - activate test-environment
  # We need wheel installed to build wheels
  - "%PYTHON%\\python.exe -m pip install wheel"

build: off

test_script:
  - activate test-environment
  - "build.cmd %PYTHON%\\python.exe setup.py test"

after_test:
  - activate test-environment
  - "build.cmd %PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  - path: dist\*
