environment:
  matrix:
    # Python 2.7
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"

    # Python 3.4
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python34-x64"

    # Python 3.5
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"

    # Python 3.6
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"

install:
  # We need wheel installed to build wheels, and pipwin for windows things
  - "%PYTHON%\\python.exe -m pip install wheel"
  - "%PYTHON%\\python.exe -m pip install https://github.com/staticfloat/pipwin/archive/sf/the_end_of_obfuscation.tar.gz"
  # Install numpy, scipy and matplotlib from pipwin
  - "%PYTHON%\\Scripts\\pipwin.exe install numpy scipy matplotlib"

build: off

test_script:
  - activate test-environment
  - "build.cmd %PYTHON%\\python.exe setup.py test"

after_test:
  - activate test-environment
  - "build.cmd %PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  - path: dist\*
