environment:
  matrix:
    # Python 2.7
    # - PYTHON: "C:\\Python27"
    #   PYTHON_VERSION: 2.7
    # - PYTHON: "C:\\Python27-x64"
    #   PYTHON_VERSION: 2.7
    #
    # # Python 3.4
    # - PYTHON: "C:\\Python34"
    #   PYTHON_VERSION: 3.4
    # - PYTHON: "C:\\Python34-x64"
    #   PYTHON_VERSION: 3.4
    #
    # # Python 3.5
    # - PYTHON: "C:\\Python35"
    #   PYTHON_VERSION: 3.5
    # - PYTHON: "C:\\Python35-x64"
    #   PYTHON_VERSION: 3.5

    # Python 3.6
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: 3.6
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: 3.6

install:
  # We need wheel installed to build wheels, and pipwin for windows things
  - "%PYTHON%\\python.exe -m pip install wheel"
  - "%PYTHON%\\python.exe -m pip install https://github.com/staticfloat/pipwin/archive/master.tar.gz"
  # Install numpy, scipy and matplotlib from pipwin
  - "%PYTHON%\\Scripts\\pipwin.exe install numpy"
  - "%PYTHON%\\Scripts\\pipwin.exe install scipy"
  - "%PYTHON%\\Scripts\\pipwin.exe install matplotlib"

build: off

test_script:
  - "build.cmd %PYTHON%\\python.exe setup.py test"

after_test:
  - "build.cmd %PYTHON%\\python.exe setup.py bdist_wheel"

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))


artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  - path: dist\*
  # I want to see the pretty picturesss
  - path: figures\*
